# Generated by Django 5.0.7 on 2024-07-17 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fin_analysis.account')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['account_id', 'create_by', 'create_at'], name='fin_analysi_account_3718ea_idx')],
            },
        ),
    ]
