# Generated by Django 5.0.7 on 2024-07-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_analysis', '0002_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='adj_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
