# Generated by Django 5.0.7 on 2024-07-21 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_analysis', '0004_news'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='datas',
            name='fin_analysi_account_4ffa51_idx',
        ),
        migrations.AddIndex(
            model_name='datas',
            index=models.Index(fields=['actions_id'], name='fin_analysi_actions_e49a3c_idx'),
        ),
    ]
